### ISSUE TITLE
表格无法正确显示

### ISSUE THREAD

**Issue by whg517** [keelii/socket-programming-in-python-cn#3]
`应用程序类` 下面的一个表格无法正确显示，希望及时修改。谢谢

一下是页面显示内容

---

看起来就像这样：

步骤 | 端 | 动作/消息内容 :- | :- | :- 1 | 客户端 | 发送带有请求内容的消息 2 | 服务端 | 接收并处理请求消息 3 | 服务端 | 发送有响应内容的消息 4 | 客户端 | 接收并处理响应消息

---

**Comment by keelii** [comment]
@whg517 你是怎么看的呢？我这看网页版和markdown版都了是正常的。

**Comment by whg517** [comment]
> @whg517 你是怎么看的呢？我这看网页版和markdown版都了是正常的。

你好，我是从 google 搜索第一条。https://keelii.com/2018/09/24/socket-programming-in-python/

**Comment by keelii** [comment]
@whg517 已经修复了，多谢提醒 😀
